/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jolt_TempAllocatorImpl */

#ifndef _Included_jolt_TempAllocatorImpl
#define _Included_jolt_TempAllocatorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jolt_TempAllocatorImpl
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jolt_TempAllocatorImpl__1create
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
