/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jolt_BodyID */

#ifndef _Included_jolt_BodyID
#define _Included_jolt_BodyID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jolt_BodyID
 * Method:    _ofRaw
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jolt_BodyID__1ofRaw
  (JNIEnv *, jclass, jint);

/*
 * Class:     jolt_BodyID
 * Method:    _of
 * Signature: (IB)J
 */
JNIEXPORT jlong JNICALL Java_jolt_BodyID__1of
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     jolt_BodyID
 * Method:    _getIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jolt_BodyID__1getIndex
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jolt_BodyID
 * Method:    _getSequenceNumber
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_jolt_BodyID__1getSequenceNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jolt_BodyID
 * Method:    _isInvalid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jolt_BodyID__1isInvalid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jolt_BodyID
 * Method:    _isEqual
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_jolt_BodyID__1isEqual
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
