/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jolt_physics_collision_shape_SubShapeIDPair */

#ifndef _Included_jolt_physics_collision_shape_SubShapeIDPair
#define _Included_jolt_physics_collision_shape_SubShapeIDPair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jolt_physics_collision_shape_SubShapeIDPair
 * Method:    _getBody1ID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jolt_physics_collision_shape_SubShapeIDPair__1getBody1ID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jolt_physics_collision_shape_SubShapeIDPair
 * Method:    _getSubShape1ID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jolt_physics_collision_shape_SubShapeIDPair__1getSubShape1ID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jolt_physics_collision_shape_SubShapeIDPair
 * Method:    _getBody2ID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jolt_physics_collision_shape_SubShapeIDPair__1getBody2ID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jolt_physics_collision_shape_SubShapeIDPair
 * Method:    _getSubShape2ID
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jolt_physics_collision_shape_SubShapeIDPair__1getSubShape2ID
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jolt_physics_collision_shape_SubShapeIDPair
 * Method:    _hash
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jolt_physics_collision_shape_SubShapeIDPair__1hash
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
