/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jolt_JoltNativeLoader */

#ifndef _Included_jolt_JoltNativeLoader
#define _Included_jolt_JoltNativeLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jolt_JoltNativeLoader
 * Method:    _initThreadManager
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jolt_JoltNativeLoader__1initThreadManager
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
