[versions]

jniGlue = "1.0.0"
findBugs = "3.0.2"

[libraries]

jniGlueAnnotations = { group = "io.github.aecsocket", name = "jni-glue-annotations", version.ref = "jniGlue" }
jniGlueProcessor = { group = "io.github.aecsocket", name = "jni-glue-processor", version.ref = "jniGlue" }

findBugs = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "findBugs" }
