// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$114 {

    static final FunctionDescriptor JPC_DistanceConstraintSettings_GetMaxDistance$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_GetMaxDistance$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_GetMaxDistance",
        constants$114.JPC_DistanceConstraintSettings_GetMaxDistance$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_SetMaxDistance$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_SetMaxDistance$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_SetMaxDistance",
        constants$114.JPC_DistanceConstraintSettings_SetMaxDistance$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_GetFrequency$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_GetFrequency$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_GetFrequency",
        constants$114.JPC_DistanceConstraintSettings_GetFrequency$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_SetFrequency$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_SetFrequency$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_SetFrequency",
        constants$114.JPC_DistanceConstraintSettings_SetFrequency$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_GetDamping$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_GetDamping$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_GetDamping",
        constants$114.JPC_DistanceConstraintSettings_GetDamping$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_SetDamping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_SetDamping$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_SetDamping",
        constants$114.JPC_DistanceConstraintSettings_SetDamping$FUNC
    );
}


