// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$112 {

    static final FunctionDescriptor JPC_FixedConstraintSettings_SetAxisX2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_FixedConstraintSettings_SetAxisX2$MH = RuntimeHelper.downcallHandle(
        "JPC_FixedConstraintSettings_SetAxisX2",
        constants$112.JPC_FixedConstraintSettings_SetAxisX2$FUNC
    );
    static final FunctionDescriptor JPC_FixedConstraintSettings_GetAxisY2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_FixedConstraintSettings_GetAxisY2$MH = RuntimeHelper.downcallHandle(
        "JPC_FixedConstraintSettings_GetAxisY2",
        constants$112.JPC_FixedConstraintSettings_GetAxisY2$FUNC
    );
    static final FunctionDescriptor JPC_FixedConstraintSettings_SetAxisY2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_FixedConstraintSettings_SetAxisY2$MH = RuntimeHelper.downcallHandle(
        "JPC_FixedConstraintSettings_SetAxisY2",
        constants$112.JPC_FixedConstraintSettings_SetAxisY2$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_Create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle JPC_DistanceConstraintSettings_Create$MH = RuntimeHelper.downcallHandleVariadic(
        "JPC_DistanceConstraintSettings_Create",
        constants$112.JPC_DistanceConstraintSettings_Create$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_GetSpace$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_GetSpace$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_GetSpace",
        constants$112.JPC_DistanceConstraintSettings_GetSpace$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraintSettings_SetSpace$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraintSettings_SetSpace$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraintSettings_SetSpace",
        constants$112.JPC_DistanceConstraintSettings_SetSpace$FUNC
    );
}


