// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$89 {

    static final FunctionDescriptor JPC_DistanceConstraint_SetDistance$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraint_SetDistance$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraint_SetDistance",
        constants$89.JPC_DistanceConstraint_SetDistance$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraint_GetMinDistance$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraint_GetMinDistance$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraint_GetMinDistance",
        constants$89.JPC_DistanceConstraint_GetMinDistance$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraint_GetMaxDistance$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraint_GetMaxDistance$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraint_GetMaxDistance",
        constants$89.JPC_DistanceConstraint_GetMaxDistance$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraint_SetFrequency$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraint_SetFrequency$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraint_SetFrequency",
        constants$89.JPC_DistanceConstraint_SetFrequency$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraint_GetFrequency$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraint_GetFrequency$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraint_GetFrequency",
        constants$89.JPC_DistanceConstraint_GetFrequency$FUNC
    );
    static final FunctionDescriptor JPC_DistanceConstraint_SetDamping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_DistanceConstraint_SetDamping$MH = RuntimeHelper.downcallHandle(
        "JPC_DistanceConstraint_SetDamping",
        constants$89.JPC_DistanceConstraint_SetDamping$FUNC
    );
}


