// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$100 {

    static final FunctionDescriptor JPC_SwingTwistConstraint_SetTargetAngularVelocityCS$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetTargetAngularVelocityCS$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetTargetAngularVelocityCS",
        constants$100.JPC_SwingTwistConstraint_SetTargetAngularVelocityCS$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetTargetAngularVelocityCS$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetTargetAngularVelocityCS$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetTargetAngularVelocityCS",
        constants$100.JPC_SwingTwistConstraint_GetTargetAngularVelocityCS$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_SetTargetOrientationCS$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetTargetOrientationCS$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetTargetOrientationCS",
        constants$100.JPC_SwingTwistConstraint_SetTargetOrientationCS$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetTargetOrientationCS$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetTargetOrientationCS$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetTargetOrientationCS",
        constants$100.JPC_SwingTwistConstraint_GetTargetOrientationCS$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_SetTargetOrientationBS$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetTargetOrientationBS$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetTargetOrientationBS",
        constants$100.JPC_SwingTwistConstraint_SetTargetOrientationBS$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetTotalLambdaPosition$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetTotalLambdaPosition$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetTotalLambdaPosition",
        constants$100.JPC_SwingTwistConstraint_GetTotalLambdaPosition$FUNC
    );
}


