// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$101 {

    static final FunctionDescriptor JPC_SwingTwistConstraint_GetMaxFrictionTorque$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetMaxFrictionTorque$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetMaxFrictionTorque",
        constants$101.JPC_SwingTwistConstraint_GetMaxFrictionTorque$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_SetSwingMotorState$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetSwingMotorState$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetSwingMotorState",
        constants$101.JPC_SwingTwistConstraint_SetSwingMotorState$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetSwingMotorState$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetSwingMotorState$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetSwingMotorState",
        constants$101.JPC_SwingTwistConstraint_GetSwingMotorState$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_SetTwistMotorState$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetTwistMotorState$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetTwistMotorState",
        constants$101.JPC_SwingTwistConstraint_SetTwistMotorState$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetTwistMotorState$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetTwistMotorState$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetTwistMotorState",
        constants$101.JPC_SwingTwistConstraint_GetTwistMotorState$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_SetTargetAngularVelocityCS$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetTargetAngularVelocityCS$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetTargetAngularVelocityCS",
        constants$101.JPC_SwingTwistConstraint_SetTargetAngularVelocityCS$FUNC
    );
}


