// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$97 {

    static final FunctionDescriptor JPC_SliderConstraint_HasLimits$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_HasLimits$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_HasLimits",
        constants$97.JPC_SliderConstraint_HasLimits$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_SetFrequency$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_SetFrequency$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_SetFrequency",
        constants$97.JPC_SliderConstraint_SetFrequency$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_GetFrequency$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_GetFrequency$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_GetFrequency",
        constants$97.JPC_SliderConstraint_GetFrequency$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_SetDamping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_SetDamping$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_SetDamping",
        constants$97.JPC_SliderConstraint_SetDamping$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_GetDamping$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_GetDamping$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_GetDamping",
        constants$97.JPC_SliderConstraint_GetDamping$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_GetTotalLambdaPosition$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_GetTotalLambdaPosition$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_GetTotalLambdaPosition",
        constants$97.JPC_SliderConstraint_GetTotalLambdaPosition$FUNC
    );
}


