// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$21 {

    static final FunctionDescriptor JPC_PhysicsSettings_SetDefault$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSettings_SetDefault$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSettings_SetDefault",
        constants$21.JPC_PhysicsSettings_SetDefault$FUNC
    );
    static final FunctionDescriptor JPC_CollideShapeResult_GetEarlyOutFraction$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_CollideShapeResult_GetEarlyOutFraction$MH = RuntimeHelper.downcallHandle(
        "JPC_CollideShapeResult_GetEarlyOutFraction",
        constants$21.JPC_CollideShapeResult_GetEarlyOutFraction$FUNC
    );
    static final FunctionDescriptor JPC_CollideShapeResult_Reversed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_CollideShapeResult_Reversed$MH = RuntimeHelper.downcallHandle(
        "JPC_CollideShapeResult_Reversed",
        constants$21.JPC_CollideShapeResult_Reversed$FUNC
    );
    static final FunctionDescriptor JPC_RayCastSettings_SetDefault$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_RayCastSettings_SetDefault$MH = RuntimeHelper.downcallHandle(
        "JPC_RayCastSettings_SetDefault",
        constants$21.JPC_RayCastSettings_SetDefault$FUNC
    );
    static final FunctionDescriptor JPC_CollideShapeSettings_SetDefault$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_CollideShapeSettings_SetDefault$MH = RuntimeHelper.downcallHandle(
        "JPC_CollideShapeSettings_SetDefault",
        constants$21.JPC_CollideShapeSettings_SetDefault$FUNC
    );
    static final FunctionDescriptor JPC_ShapeCastSettings_SetDefault$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ShapeCastSettings_SetDefault$MH = RuntimeHelper.downcallHandle(
        "JPC_ShapeCastSettings_SetDefault",
        constants$21.JPC_ShapeCastSettings_SetDefault$FUNC
    );
}


