// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$132 {

    static final FunctionDescriptor JPC_SixDOFConstraintSettings_SetPosition1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SixDOFConstraintSettings_SetPosition1$MH = RuntimeHelper.downcallHandle(
        "JPC_SixDOFConstraintSettings_SetPosition1",
        constants$132.JPC_SixDOFConstraintSettings_SetPosition1$FUNC
    );
    static final FunctionDescriptor JPC_SixDOFConstraintSettings_GetAxisX1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SixDOFConstraintSettings_GetAxisX1$MH = RuntimeHelper.downcallHandle(
        "JPC_SixDOFConstraintSettings_GetAxisX1",
        constants$132.JPC_SixDOFConstraintSettings_GetAxisX1$FUNC
    );
    static final FunctionDescriptor JPC_SixDOFConstraintSettings_SetAxisX1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SixDOFConstraintSettings_SetAxisX1$MH = RuntimeHelper.downcallHandle(
        "JPC_SixDOFConstraintSettings_SetAxisX1",
        constants$132.JPC_SixDOFConstraintSettings_SetAxisX1$FUNC
    );
    static final FunctionDescriptor JPC_SixDOFConstraintSettings_GetAxisY1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SixDOFConstraintSettings_GetAxisY1$MH = RuntimeHelper.downcallHandle(
        "JPC_SixDOFConstraintSettings_GetAxisY1",
        constants$132.JPC_SixDOFConstraintSettings_GetAxisY1$FUNC
    );
    static final FunctionDescriptor JPC_SixDOFConstraintSettings_SetAxisY1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SixDOFConstraintSettings_SetAxisY1$MH = RuntimeHelper.downcallHandle(
        "JPC_SixDOFConstraintSettings_SetAxisY1",
        constants$132.JPC_SixDOFConstraintSettings_SetAxisY1$FUNC
    );
    static final FunctionDescriptor JPC_SixDOFConstraintSettings_GetPosition2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SixDOFConstraintSettings_GetPosition2$MH = RuntimeHelper.downcallHandle(
        "JPC_SixDOFConstraintSettings_GetPosition2",
        constants$132.JPC_SixDOFConstraintSettings_GetPosition2$FUNC
    );
}


