// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$97 {

    static final FunctionDescriptor JPC_SwingTwistConstraint_GetConstraintToBody1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetConstraintToBody1$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetConstraintToBody1",
        constants$97.JPC_SwingTwistConstraint_GetConstraintToBody1$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetConstraintToBody2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetConstraintToBody2$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetConstraintToBody2",
        constants$97.JPC_SwingTwistConstraint_GetConstraintToBody2$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetNormalHalfConeAngle$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetNormalHalfConeAngle$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetNormalHalfConeAngle",
        constants$97.JPC_SwingTwistConstraint_GetNormalHalfConeAngle$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_SetNormalHalfConeAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetNormalHalfConeAngle$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetNormalHalfConeAngle",
        constants$97.JPC_SwingTwistConstraint_SetNormalHalfConeAngle$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_GetPlaneHalfConeAngle$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_GetPlaneHalfConeAngle$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_GetPlaneHalfConeAngle",
        constants$97.JPC_SwingTwistConstraint_GetPlaneHalfConeAngle$FUNC
    );
    static final FunctionDescriptor JPC_SwingTwistConstraint_SetPlaneHalfConeAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_SwingTwistConstraint_SetPlaneHalfConeAngle$MH = RuntimeHelper.downcallHandle(
        "JPC_SwingTwistConstraint_SetPlaneHalfConeAngle",
        constants$97.JPC_SwingTwistConstraint_SetPlaneHalfConeAngle$FUNC
    );
}


