// Generated by jextract

package jolt.headers_f;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$120 {

    static final FunctionDescriptor JPC_ConeConstraintSettings_GetSpace$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_GetSpace$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_GetSpace",
        constants$120.JPC_ConeConstraintSettings_GetSpace$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_SetSpace$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_SetSpace$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_SetSpace",
        constants$120.JPC_ConeConstraintSettings_SetSpace$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_GetPoint1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_GetPoint1$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_GetPoint1",
        constants$120.JPC_ConeConstraintSettings_GetPoint1$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_SetPoint1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_SetPoint1$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_SetPoint1",
        constants$120.JPC_ConeConstraintSettings_SetPoint1$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_GetTwistAxis1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_GetTwistAxis1$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_GetTwistAxis1",
        constants$120.JPC_ConeConstraintSettings_GetTwistAxis1$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_SetTwistAxis1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_SetTwistAxis1$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_SetTwistAxis1",
        constants$120.JPC_ConeConstraintSettings_SetTwistAxis1$FUNC
    );
}


