// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$28 {

    static final FunctionDescriptor JPC_PhysicsSystem_SetCombineFriction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_SetCombineFriction$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_SetCombineFriction",
        constants$28.JPC_PhysicsSystem_SetCombineFriction$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_SetCombineRestitution$x0$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_SetCombineRestitution$x0$MH = RuntimeHelper.downcallHandle(
        constants$28.JPC_PhysicsSystem_SetCombineRestitution$x0$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_SetCombineRestitution$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_SetCombineRestitution$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_SetCombineRestitution",
        constants$28.JPC_PhysicsSystem_SetCombineRestitution$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_GetNumBodies$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_GetNumBodies$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_GetNumBodies",
        constants$28.JPC_PhysicsSystem_GetNumBodies$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_GetNumActiveBodies$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_GetNumActiveBodies$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_GetNumActiveBodies",
        constants$28.JPC_PhysicsSystem_GetNumActiveBodies$FUNC
    );
}


