// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$121 {

    static final FunctionDescriptor JPC_ConeConstraintSettings_GetPoint2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_GetPoint2$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_GetPoint2",
        constants$121.JPC_ConeConstraintSettings_GetPoint2$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_SetPoint2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_SetPoint2$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_SetPoint2",
        constants$121.JPC_ConeConstraintSettings_SetPoint2$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_GetTwistAxis2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_GetTwistAxis2$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_GetTwistAxis2",
        constants$121.JPC_ConeConstraintSettings_GetTwistAxis2$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_SetTwistAxis2$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_SetTwistAxis2$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_SetTwistAxis2",
        constants$121.JPC_ConeConstraintSettings_SetTwistAxis2$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_GetHalfConeAngle$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_GetHalfConeAngle$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_GetHalfConeAngle",
        constants$121.JPC_ConeConstraintSettings_GetHalfConeAngle$FUNC
    );
    static final FunctionDescriptor JPC_ConeConstraintSettings_SetHalfConeAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_ConeConstraintSettings_SetHalfConeAngle$MH = RuntimeHelper.downcallHandle(
        "JPC_ConeConstraintSettings_SetHalfConeAngle",
        constants$121.JPC_ConeConstraintSettings_SetHalfConeAngle$FUNC
    );
}


