// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$32 {

    static final FunctionDescriptor JPC_PhysicsSystem_GetNarrowPhaseQuery$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_GetNarrowPhaseQuery$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_GetNarrowPhaseQuery",
        constants$32.JPC_PhysicsSystem_GetNarrowPhaseQuery$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_GetNarrowPhaseQueryNoLock$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_GetNarrowPhaseQueryNoLock$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_GetNarrowPhaseQueryNoLock",
        constants$32.JPC_PhysicsSystem_GetNarrowPhaseQueryNoLock$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_AddConstraint$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_AddConstraint$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_AddConstraint",
        constants$32.JPC_PhysicsSystem_AddConstraint$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_RemoveConstraint$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_RemoveConstraint$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_RemoveConstraint",
        constants$32.JPC_PhysicsSystem_RemoveConstraint$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_AddConstraints$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_AddConstraints$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_AddConstraints",
        constants$32.JPC_PhysicsSystem_AddConstraints$FUNC
    );
    static final FunctionDescriptor JPC_PhysicsSystem_RemoveConstraints$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle JPC_PhysicsSystem_RemoveConstraints$MH = RuntimeHelper.downcallHandle(
        "JPC_PhysicsSystem_RemoveConstraints",
        constants$32.JPC_PhysicsSystem_RemoveConstraints$FUNC
    );
}


