// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$91 {

    static final FunctionDescriptor JPC_HingeConstraint_GetMotorSettings$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_HingeConstraint_GetMotorSettings$MH = RuntimeHelper.downcallHandle(
        "JPC_HingeConstraint_GetMotorSettings",
        constants$91.JPC_HingeConstraint_GetMotorSettings$FUNC
    );
    static final FunctionDescriptor JPC_HingeConstraint_SetMotorState$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_CHAR$LAYOUT
    );
    static final MethodHandle JPC_HingeConstraint_SetMotorState$MH = RuntimeHelper.downcallHandle(
        "JPC_HingeConstraint_SetMotorState",
        constants$91.JPC_HingeConstraint_SetMotorState$FUNC
    );
    static final FunctionDescriptor JPC_HingeConstraint_GetMotorState$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_HingeConstraint_GetMotorState$MH = RuntimeHelper.downcallHandle(
        "JPC_HingeConstraint_GetMotorState",
        constants$91.JPC_HingeConstraint_GetMotorState$FUNC
    );
    static final FunctionDescriptor JPC_HingeConstraint_SetTargetAngularVelocity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_HingeConstraint_SetTargetAngularVelocity$MH = RuntimeHelper.downcallHandle(
        "JPC_HingeConstraint_SetTargetAngularVelocity",
        constants$91.JPC_HingeConstraint_SetTargetAngularVelocity$FUNC
    );
    static final FunctionDescriptor JPC_HingeConstraint_GetTargetAngularVelocity$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_HingeConstraint_GetTargetAngularVelocity$MH = RuntimeHelper.downcallHandle(
        "JPC_HingeConstraint_GetTargetAngularVelocity",
        constants$91.JPC_HingeConstraint_GetTargetAngularVelocity$FUNC
    );
    static final FunctionDescriptor JPC_HingeConstraint_SetTargetAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_HingeConstraint_SetTargetAngle$MH = RuntimeHelper.downcallHandle(
        "JPC_HingeConstraint_SetTargetAngle",
        constants$91.JPC_HingeConstraint_SetTargetAngle$FUNC
    );
}


