// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$35 {

    static final FunctionDescriptor JPC_CollidePointCollector_ForceEarlyOut$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_CollidePointCollector_ForceEarlyOut$MH = RuntimeHelper.downcallHandle(
        "JPC_CollidePointCollector_ForceEarlyOut",
        constants$35.JPC_CollidePointCollector_ForceEarlyOut$FUNC
    );
    static final FunctionDescriptor JPC_CollidePointCollector_ShouldEarlyOut$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_CollidePointCollector_ShouldEarlyOut$MH = RuntimeHelper.downcallHandle(
        "JPC_CollidePointCollector_ShouldEarlyOut",
        constants$35.JPC_CollidePointCollector_ShouldEarlyOut$FUNC
    );
    static final FunctionDescriptor JPC_CollideShapeCollector_ForceEarlyOut$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_CollideShapeCollector_ForceEarlyOut$MH = RuntimeHelper.downcallHandle(
        "JPC_CollideShapeCollector_ForceEarlyOut",
        constants$35.JPC_CollideShapeCollector_ForceEarlyOut$FUNC
    );
    static final FunctionDescriptor JPC_CollideShapeCollector_ShouldEarlyOut$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_CollideShapeCollector_ShouldEarlyOut$MH = RuntimeHelper.downcallHandle(
        "JPC_CollideShapeCollector_ShouldEarlyOut",
        constants$35.JPC_CollideShapeCollector_ShouldEarlyOut$FUNC
    );
    static final FunctionDescriptor JPC_TransformedShapeCollector_ForceEarlyOut$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_TransformedShapeCollector_ForceEarlyOut$MH = RuntimeHelper.downcallHandle(
        "JPC_TransformedShapeCollector_ForceEarlyOut",
        constants$35.JPC_TransformedShapeCollector_ForceEarlyOut$FUNC
    );
    static final FunctionDescriptor JPC_TransformedShapeCollector_ShouldEarlyOut$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_TransformedShapeCollector_ShouldEarlyOut$MH = RuntimeHelper.downcallHandle(
        "JPC_TransformedShapeCollector_ShouldEarlyOut",
        constants$35.JPC_TransformedShapeCollector_ShouldEarlyOut$FUNC
    );
}


