// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$21 {

    static final FunctionDescriptor JPC_MotionProperties_GetMotionQuality$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_MotionProperties_GetMotionQuality$MH = RuntimeHelper.downcallHandle(
        "JPC_MotionProperties_GetMotionQuality",
        constants$21.JPC_MotionProperties_GetMotionQuality$FUNC
    );
    static final FunctionDescriptor JPC_MotionProperties_GetLinearVelocity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_MotionProperties_GetLinearVelocity$MH = RuntimeHelper.downcallHandle(
        "JPC_MotionProperties_GetLinearVelocity",
        constants$21.JPC_MotionProperties_GetLinearVelocity$FUNC
    );
    static final FunctionDescriptor JPC_MotionProperties_SetLinearVelocity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_MotionProperties_SetLinearVelocity$MH = RuntimeHelper.downcallHandle(
        "JPC_MotionProperties_SetLinearVelocity",
        constants$21.JPC_MotionProperties_SetLinearVelocity$FUNC
    );
    static final FunctionDescriptor JPC_MotionProperties_SetLinearVelocityClamped$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_MotionProperties_SetLinearVelocityClamped$MH = RuntimeHelper.downcallHandle(
        "JPC_MotionProperties_SetLinearVelocityClamped",
        constants$21.JPC_MotionProperties_SetLinearVelocityClamped$FUNC
    );
    static final FunctionDescriptor JPC_MotionProperties_GetAngularVelocity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_MotionProperties_GetAngularVelocity$MH = RuntimeHelper.downcallHandle(
        "JPC_MotionProperties_GetAngularVelocity",
        constants$21.JPC_MotionProperties_GetAngularVelocity$FUNC
    );
    static final FunctionDescriptor JPC_MotionProperties_SetAngularVelocity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_MotionProperties_SetAngularVelocity$MH = RuntimeHelper.downcallHandle(
        "JPC_MotionProperties_SetAngularVelocity",
        constants$21.JPC_MotionProperties_SetAngularVelocity$FUNC
    );
}


