// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$96 {

    static final FunctionDescriptor JPC_SliderConstraint_GetTargetVelocity$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_GetTargetVelocity$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_GetTargetVelocity",
        constants$96.JPC_SliderConstraint_GetTargetVelocity$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_SetTargetPosition$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_SetTargetPosition$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_SetTargetPosition",
        constants$96.JPC_SliderConstraint_SetTargetPosition$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_GetTargetPosition$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_GetTargetPosition$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_GetTargetPosition",
        constants$96.JPC_SliderConstraint_GetTargetPosition$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_SetLimits$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_SetLimits$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_SetLimits",
        constants$96.JPC_SliderConstraint_SetLimits$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_GetLimitsMin$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_GetLimitsMin$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_GetLimitsMin",
        constants$96.JPC_SliderConstraint_GetLimitsMin$FUNC
    );
    static final FunctionDescriptor JPC_SliderConstraint_GetLimitsMax$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_SliderConstraint_GetLimitsMax$MH = RuntimeHelper.downcallHandle(
        "JPC_SliderConstraint_GetLimitsMax",
        constants$96.JPC_SliderConstraint_GetLimitsMax$FUNC
    );
}


