// Generated by jextract

package jolt.headers;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class JPC_CollisionGroup {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("filter"),
        Constants$root.C_INT$LAYOUT.withName("group_id"),
        Constants$root.C_INT$LAYOUT.withName("sub_group_id")
    ).withName("JPC_CollisionGroup");
    public static MemoryLayout $LAYOUT() {
        return JPC_CollisionGroup.$struct$LAYOUT;
    }
    static final VarHandle filter$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("filter"));
    public static VarHandle filter$VH() {
        return JPC_CollisionGroup.filter$VH;
    }
    public static MemoryAddress filter$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)JPC_CollisionGroup.filter$VH.get(seg);
    }
    public static void filter$set( MemorySegment seg, MemoryAddress x) {
        JPC_CollisionGroup.filter$VH.set(seg, x);
    }
    public static MemoryAddress filter$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)JPC_CollisionGroup.filter$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void filter$set(MemorySegment seg, long index, MemoryAddress x) {
        JPC_CollisionGroup.filter$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle group_id$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("group_id"));
    public static VarHandle group_id$VH() {
        return JPC_CollisionGroup.group_id$VH;
    }
    public static int group_id$get(MemorySegment seg) {
        return (int)JPC_CollisionGroup.group_id$VH.get(seg);
    }
    public static void group_id$set( MemorySegment seg, int x) {
        JPC_CollisionGroup.group_id$VH.set(seg, x);
    }
    public static int group_id$get(MemorySegment seg, long index) {
        return (int)JPC_CollisionGroup.group_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void group_id$set(MemorySegment seg, long index, int x) {
        JPC_CollisionGroup.group_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sub_group_id$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("sub_group_id"));
    public static VarHandle sub_group_id$VH() {
        return JPC_CollisionGroup.sub_group_id$VH;
    }
    public static int sub_group_id$get(MemorySegment seg) {
        return (int)JPC_CollisionGroup.sub_group_id$VH.get(seg);
    }
    public static void sub_group_id$set( MemorySegment seg, int x) {
        JPC_CollisionGroup.sub_group_id$VH.set(seg, x);
    }
    public static int sub_group_id$get(MemorySegment seg, long index) {
        return (int)JPC_CollisionGroup.sub_group_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sub_group_id$set(MemorySegment seg, long index, int x) {
        JPC_CollisionGroup.sub_group_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


