// Generated by jextract

package jolt.headers_d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$62 {

    static final FunctionDescriptor JPC_ConvexShape_SetDensity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle JPC_ConvexShape_SetDensity$MH = RuntimeHelper.downcallHandle(
        "JPC_ConvexShape_SetDensity",
        constants$62.JPC_ConvexShape_SetDensity$FUNC
    );
    static final FunctionDescriptor JPC_ConvexShape_GetDensity$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ConvexShape_GetDensity$MH = RuntimeHelper.downcallHandle(
        "JPC_ConvexShape_GetDensity",
        constants$62.JPC_ConvexShape_GetDensity$FUNC
    );
    static final FunctionDescriptor JPC_DecoratedShape_GetInnerShape$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_DecoratedShape_GetInnerShape$MH = RuntimeHelper.downcallHandle(
        "JPC_DecoratedShape_GetInnerShape",
        constants$62.JPC_DecoratedShape_GetInnerShape$FUNC
    );
    static final FunctionDescriptor JPC_ScaledShape_Create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ScaledShape_Create$MH = RuntimeHelper.downcallHandle(
        "JPC_ScaledShape_Create",
        constants$62.JPC_ScaledShape_Create$FUNC
    );
    static final FunctionDescriptor JPC_ScaledShape_GetScale$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_ScaledShape_GetScale$MH = RuntimeHelper.downcallHandle(
        "JPC_ScaledShape_GetScale",
        constants$62.JPC_ScaledShape_GetScale$FUNC
    );
    static final FunctionDescriptor JPC_RotatedTranslatedShape_Create$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JPC_RotatedTranslatedShape_Create$MH = RuntimeHelper.downcallHandle(
        "JPC_RotatedTranslatedShape_Create",
        constants$62.JPC_RotatedTranslatedShape_Create$FUNC
    );
}


