// Generated by jextract

package jolt.headers_d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class JPC_SubShapeIDCreator {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("id"),
        Constants$root.C_INT$LAYOUT.withName("current_bit")
    ).withName("JPC_SubShapeIDCreator");
    public static MemoryLayout $LAYOUT() {
        return JPC_SubShapeIDCreator.$struct$LAYOUT;
    }
    static final VarHandle id$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("id"));
    public static VarHandle id$VH() {
        return JPC_SubShapeIDCreator.id$VH;
    }
    public static int id$get(MemorySegment seg) {
        return (int)JPC_SubShapeIDCreator.id$VH.get(seg);
    }
    public static void id$set( MemorySegment seg, int x) {
        JPC_SubShapeIDCreator.id$VH.set(seg, x);
    }
    public static int id$get(MemorySegment seg, long index) {
        return (int)JPC_SubShapeIDCreator.id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void id$set(MemorySegment seg, long index, int x) {
        JPC_SubShapeIDCreator.id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle current_bit$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("current_bit"));
    public static VarHandle current_bit$VH() {
        return JPC_SubShapeIDCreator.current_bit$VH;
    }
    public static int current_bit$get(MemorySegment seg) {
        return (int)JPC_SubShapeIDCreator.current_bit$VH.get(seg);
    }
    public static void current_bit$set( MemorySegment seg, int x) {
        JPC_SubShapeIDCreator.current_bit$VH.set(seg, x);
    }
    public static int current_bit$get(MemorySegment seg, long index) {
        return (int)JPC_SubShapeIDCreator.current_bit$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void current_bit$set(MemorySegment seg, long index, int x) {
        JPC_SubShapeIDCreator.current_bit$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


