name: "Build"

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            publish-core: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: "Setup Java"
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
      - name: "Run Gradle build"
        run: ./gradlew --stacktrace build
      - name: "sh: Get version type "
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          VERSION_TYPE=$(./gradlew -q --console=plain --no-daemon printVersionType)
          echo VERSION_TYPE=$VERSION_TYPE
          echo VERSION_TYPE=$VERSION_TYPE >> $GITHUB_ENV
      - name: "ps: Get version type"
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $VERSION_TYPE = ./gradlew -q --console=plain --no-daemon printVersionType
          echo VERSION_TYPE=$VERSION_TYPE
          echo VERSION_TYPE=$VERSION_TYPE >> $env:GITHUB_ENV
      - name: "Publish snapshot"
        if: ${{ env.VERSION_TYPE == 'snapshot' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: ./gradlew publish
        env:
          CI_PUBLISH_CORE: ${{ matrix.publish-core }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      - name: "Publish release"
        if: ${{ env.VERSION_TYPE == 'release' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: ./gradlew -PforceSign=true publishToSonatype closeSonatypeStagingRepository
        env:
          CI_PUBLISH_CORE: ${{ matrix.publish-core }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
